version: '3'

services:
  vmianqian:
    image: monlor/vmianqian
    container_name: vmianqian
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=vmq
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vmq
    restart: unless-stopped

volumes:
  db_data: