version: '3'

services:
  epay:
    image: monlor/epay
    container_name: epay
    volumes:
      - epay:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=epay
    restart: unless-stopped

volumes:
  epay:
  db_data: