version: '3'

services:
  tokenpay:
    image: monlor/tokenpay
    container_name: tokenpay
    volumes:
      - tokenpay:/data
    environment:
      - WEB_URL=https://token-pay.xxx.com
      - TRON_ADDRESS=xxx
      - TRON_PRO_API_KEY=xxx
      - POLYGON_ADDRESS=xxx
      - POLYGON_API_KEY=xxx
      - TG_USER_ID=111
      - TG_BOT_TOKEN=xxx
      - API_TOKEN=xxx
    ports:
      - "5001:5001"
    restart: unless-stopped

volumes:
  tokenpay: