name: build-image-manual

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: choice
        options:
        - coder-development
        - pgvector
        - epay
        - dujiaoka
        - opsutils
        - tidb-toolkit
        - jenkins
        - subconverter
        - frps
        - frpc
        - vmianqian
        - tokenpay
        - n8n
        - bepusdt
        - http-dump
        - kubectl
        - radiance-bot
        - nezha
        - weserv
        - media-unlock
        - sniproxy
        - xboard
        - ws-scrcpy
        - excalidraw
        - linkstack
        - firefox
        - mitmproxy
        - redroid
        - nginx-proxy-manager
        - authelia
      tag:
        description: 'Image tag'
      registry_target:
        description: 'Target registry for pushing images'
        required: false
        type: choice
        options:
        - ghcr
        - dockerhub
        - all
        default: 'ghcr'

env:
  PROJECT_NAME: ${{ github.event.inputs.project }}
  REGISTRY_TARGET: ${{ github.event.inputs.registry_target || 'ghcr' }}
  # github.repository as <account>/<repo>

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set tag
        id: tag
        run: |
          tag=""
          dockerfile_version=$(cat ${{ env.PROJECT_NAME }}/Dockerfile | awk '{if($1~"LABEL" && $2=="VERSION")print $3}')
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            tag=${{ github.event.inputs.tag }}
          elif [[ -n "${dockerfile_version}" ]]; then
            tag=${dockerfile_version}
          else
            echo "Image tag can not be null!"
            exit 1
          fi
          
          # Set image tags based on registry target
          if [[ "${{ env.REGISTRY_TARGET }}" == "ghcr" || "${{ env.REGISTRY_TARGET }}" == "all" ]]; then
            ghcr_image_name=ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}
            ghcr_tags=${ghcr_image_name}:${tag},${ghcr_image_name}:latest
            echo "GHCR_TAGS=${ghcr_tags}" >> $GITHUB_ENV
          fi
          
          if [[ "${{ env.REGISTRY_TARGET }}" == "dockerhub" || "${{ env.REGISTRY_TARGET }}" == "all" ]]; then
            dockerhub_image_name=${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}
            dockerhub_tags=${dockerhub_image_name}:${tag},${dockerhub_image_name}:latest
            echo "DOCKERHUB_TAGS=${dockerhub_tags}" >> $GITHUB_ENV
          fi
          
          # Combine all tags for build
          all_tags=""
          if [[ -n "${ghcr_tags}" ]]; then
            all_tags="${ghcr_tags}"
          fi
          if [[ -n "${dockerhub_tags}" ]]; then
            if [[ -n "${all_tags}" ]]; then
              all_tags="${all_tags},${dockerhub_tags}"
            else
              all_tags="${dockerhub_tags}"
            fi
          fi
          echo "IMAGE_TAGS=${all_tags}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.PROJECT_NAME }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PROJECT_NAME }}-

      # Login to GHCR (GitHub Container Registry)
      - name: Log into GHCR
        if: (github.event_name != 'pull_request') && (env.REGISTRY_TARGET == 'ghcr' || env.REGISTRY_TARGET == 'all')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to DockerHub
      - name: Log into DockerHub 
        if: (github.event_name != 'pull_request') && (env.REGISTRY_TARGET == 'dockerhub' || env.REGISTRY_TARGET == 'all')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3.1.1
        with:
          context: ${{ env.PROJECT_NAME }}
          push: true
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Check readme existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "${{ env.PROJECT_NAME }}/README.md"

      - name: Sync README.md to Docker Hub
        if: (steps.check_files.outputs.files_exists == 'true') && (env.REGISTRY_TARGET == 'dockerhub' || env.REGISTRY_TARGET == 'all')
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}
          readme: "${{ env.PROJECT_NAME }}/README.md"
